version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mediouna_db
    restart: always
    environment:
      POSTGRES_USER: dofy
      POSTGRES_PASSWORD: dofy
      POSTGRES_DB: mediouna_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
